import dotenv from "dotenv";
dotenv.config();

import { collection, addDoc } from "firebase/firestore";
import { db } from "./src/firebase-node.js";

export const reviews = [
  "Best gym in Gorakhpur for women! X1 Fitness offers an incredibly safe and highly comfortable workout environment.",
  "If you are looking for a unisex gym near Khorabar that is highly respectful and comfortable for female clients, this is it.",
  "Excellent atmosphere for girls. Hands down the safest and best strength training gym in the Rani Diha area.",
  "Super clean and hygienic gym in Gorakhpur with modern machines and amazing space for female cardio workouts.",
  "X1 Fitness Khorabar has a fantastic vibe. The lady fitness trainers guide you perfectly through weight loss programs.",
  "Highly professional personal training for women. Best gym near Deoria Road for female fitness transformations.",
  "Extremely clean changing rooms and secure locker facilities. Very comfortable for female clients in Gorakhpur.",
  "Top unisex fitness center in Rani Diha. Love the premium workout equipment and the completely judgment-free crowd.",
  "Best gym near me for girls in Khorabar Gorakhpur. The environment is highly motivating and secure.",
  "Great space for female functional training and crossfit. X1 Fitness is definitely the safest gym in Gorakhpur.",
  "Highly supportive trainers who design customized female diet plans and fat loss routines. Highly recommended!",
  "Superb ambiance and well-maintained cardio section. Cleanest and most hygienic gym in Gorakhpur near Rani Diha.",
  "Best place for women's weight management. Joined X1 Fitness Khorabar and the female trainers are so encouraging.",
  "Awesome unisex gym setup near Deoria Road. Peaceful environment and premium machines that are great for girls.",
  "If you want expert certified fitness trainers who understand female anatomy and fat loss, join X1 Fitness.",
  "Spacious gym floor with a very respectful crowd. Best bodybuilding and toning gym for women in Khorabar.",
  "The staff is friendly and the crowd is highly professional. Best gym in Gorakhpur for female beginners.",
  "Top notch fitness training center for women in Rani Diha Gorakhpur. Fully satisfied with the amenities.",
  "Great conditioning workouts and top-tier treadmills. Highly rated female-friendly fitness center near me.",
  "X1 Fitness is the perfect spot for regular workouts. Best unisex gym for girls in the Khorabar region.",
  "Amazing strength equipment and dumbbell selection. Very welcoming and comfortable for female clients in Gorakhpur.",
  "The trainers at X1 Fitness Khorabar are certified and ensure complete safety and correct posture during exercises.",
  "Clean changing rooms, proper parking space, and excellent ventilation. Best safe gym near Rani Diha.",
  "Top fitness spot on Deoria Road for women. Diverse equipment and an extremely energetic, respectful environment.",
  "Best gym in Gorakhpur for female fat loss programs. The trainers keep you motivated and accountable every day.",
  "Great value for money. Premium gym facilities with an elite, secure crowd for girls in Khorabar.",
  "Clean, safe, and positive vibe. Outstanding unisex gym in Gorakhpur for women's daily workouts.",
  "Best gym near me in Rani Diha. Love the friendly community and how comfortable it is for female clients.",
  "X1 Fitness has the best imported fitness equipment in Gorakhpur. Safe and smooth machinery for beginners.",
  "Highly recommended fitness center in Khorabar. Perfect for women looking for muscle toning and fat loss.",
  "Hands down the best gym near Deoria Road Gorakhpur. Very spacious, clean, and safe for female members.",
  "Professional workout environment with expert trainers. Best unisex fitness gym for girls in Rani Diha.",
  "Great cardio setup with plenty of treadmills. Excellent gym in Gorakhpur for an intense female workout.",
  "X1 Fitness Khorabar provides the best personal training experience for women. Completely transformed my fitness.",
  "Fantastic vibe for working out. Clean, well-lit, and premium gym near Rani Diha main road with top security.",
  "If you are searching for the best gym in Gorakhpur with affordable fees and a safe environment for women, this is it.",
  "Very helpful staff and top quality lady trainers. Best place for daily female strength training in Khorabar.",
  "Excellent gym facilities near Deoria Road. The crowd is highly professional, well-behaved, and respectful.",
  "X1 Fitness Rani Diha is unmatched in terms of female hygiene and machine maintenance. 5 stars!",
  "Great fitness center in Gorakhpur. Clean drinking water, ample parking, and a brilliant, safe music system.",
  "Best unisex gym near Khorabar for ladies. The personal trainers design excellent, customized workout splits.",
  "Awesome place for girls to train! Best toning, cardio, and powerlifting atmosphere for women in Gorakhpur.",
  "The trainers here are very knowledgeable about female nutrition and diets. Best gym in Rani Diha.",
  "Top class cardio and strength machines. X1 Fitness is currently the best safe gym in Gorakhpur.",
  "Brilliant experience training at X1 Fitness Khorabar. The coaches push you safely to your absolute limits.",
  "Most hygienic gym near Deoria Road. Highly disciplined and respectful environment for female fitness enthusiasts.",
  "Best gym near me in Gorakhpur for overall lifestyle transformation. Very supportive female fitness community.",
  "Amazing crossfit section and heavy lifting platforms. Best premium gym for girls in Rani Diha.",
  "X1 Fitness offers great couple packages and group discounts. Best safe unisex gym in Khorabar.",
  "Great ventilation and fully air-conditioned setup. Cleanest and best gym in Gorakhpur for women.",
  "The trainers pay equal attention to everyone, making it very comfortable for female clients in Khorabar.",
  "Best gym near Rani Diha for female strength and conditioning. The equipment quality is incredible.",
  "Excellent fitness facility on Deoria Road. Very welcoming, safe, and supportive for both men and women.",
  "X1 Fitness is the best gym in Gorakhpur for functional fitness and women's fat loss goals.",
  "Super organized gym floor with everything in its place. Best secure gym near me in Khorabar.",
  "Incredible atmosphere for a morning workout. Best female-friendly fitness center in Rani Diha Gorakhpur.",
  "The crowd is great and the trainers are super approachable. Best unisex gym for girls in Gorakhpur.",
  "Highly advanced workout machines. X1 Fitness Khorabar is definitely worth every rupee for peace of mind.",
  "Best gym near Deoria Road for functional core training, flexibility, and muscle building blocks for women.",
  "Cleanliness and safety are top priorities here. Best maintained gym in Gorakhpur near Rani Diha.",
  "Great community of fitness lovers. X1 Fitness is the absolute best safe gym in Khorabar.",
  "The trainers have solid expertise in posture correction and female strength gain. Top gym in Gorakhpur.",
  "Best gym near me for intense cardio sessions. X1 Fitness Rani Diha has a top tier, clean setup.",
  "Amazing experience so far. Highly professional and deeply respectful gym setup near Deoria Road Gorakhpur.",
  "X1 Fitness Khorabar is highly recommended for females looking for a safe, modern, and comfortable gym space.",
  "Best gym in Gorakhpur for female strength development. Outstanding trainers and respectful management.",
  "Superb layout with isolated sections for cardio and heavy lifting. Best comfortable gym in Rani Diha.",
  "Excellent support from coaches for female beginners. Best fitness center near Khorabar.",
  "The best unisex gym on Deoria Road. The respectful environment keeps you consistent with your workouts.",
  "Top tier fitness destination in Gorakhpur. X1 Fitness sets the benchmark for safe female workout spaces.",
  "Highly cooperative trainers and elite toning equipment. Best gym in Rani Diha area for women.",
  "Best gym near me in Khorabar for high intensity interval training (HIIT) and female fat loss.",
  "Very spacious gym with multiple sets of matching dumbbells. Best safe gym in Gorakhpur.",
  "X1 Fitness Khorabar offers elite level workout vibes. Perfect location, secure parking, and easy to access.",
  "Great guidance on weight management and female body transformations. Top fitness gym near Rani Diha.",
  "The perfect place to achieve your fitness goals. Best unisex gym near Deoria Road Gorakhpur for ladies.",
  "Exceptional training programs and modern infrastructure. Best premium safe gym in Gorakhpur.",
  "X1 Fitness has an incredibly motivating environment. Best gym in Khorabar for a comfortable female workout.",
  "The trainers help you track your fat loss progress precisely every week. Top gym near Rani Diha.",
  "Best fitness center near me in Gorakhpur. Perfect combination of hygiene, safety, and expert coaching.",
  "Great strength equipment and isolation machines. X1 Fitness Khorabar is highly recommended for girls.",
  "Best gym near Deoria Road for consistent body transformations. Highly satisfied with the female trainer guidance.",
  "Safe and encouraging environment for women's fitness. Best premium unisex gym in Rani Diha.",
  "The management is extremely polite and professional. Best gym in Gorakhpur overall for female clients.",
  "High quality sound system and fully vibrant energy. Best safe gym in Khorabar for daily workouts.",
  "Highly experienced trainers who specialize in women's weight loss exercises. Top gym near Rani Diha.",
  "X1 Fitness is definitely the best safe fitness hub in Gorakhpur. Brilliant amenities for ladies.",
  "Clean equipment and pristine workout floor. Best hygienic, female-friendly unisex gym in Khorabar.",
  "Best gym near me in Rani Diha Gorakhpur. Perfect for advanced female lifters and beginners alike.",
  "Awesome personal trainers who genuinely care about your health and comfort. Top gym on Deoria Road.",
  "X1 Fitness Khorabar is a standout facility. Best gym in Gorakhpur for female aesthetic goals.",
  "Great space for stretching, yoga, and core exercises. Excellent comfortable gym near Rani Diha.",
  "The membership plans are transparent and highly cost-effective. Safest gym in Khorabar for girls.",
  "Highly premium feel with top class functional training equipment. Best unisex gym in Gorakhpur.",
  "Best unisex fitness gym near Deoria Road. Safe parking space is a big plus for late evening sessions.",
  "X1 Fitness Rani Diha has a fantastic community vibe that makes female clients feel right at home.",
  "Excellent assistance for posture correction during squats and deadlifts. Top safe gym in Khorabar.",
  "Best gym in Gorakhpur for maintaining a regular fitness routine. Highly energetic and respectful coaches.",
  "Outstanding collection of plate-loaded machines. Best comfortable strength gym near Rani Diha.",
  "X1 Fitness Khorabar provides an elite level, safe workout experience for women of all age groups.",
  "Best gym near me in Gorakhpur with clean locker rooms and professional, polite staff.",
  "Super friendly atmosphere and dedicated cardio floor. Top female-friendly fitness center near Deoria Road.",
  "X1 Fitness is the most complete unisex gym in Rani Diha. Amazing interior design and great hygiene.",
  "Great guidance on proper nutrition charts and supplements for women. Best gym in Gorakhpur.",
  "Highly disciplined gym floor where weights are always racked and the crowd is civil. Best gym in Khorabar.",
  "Best fitness center near Rani Diha for female athletic performance and toning training.",
  "X1 Fitness Khorabar makes working out fun, safe, and productive. Best gym in Gorakhpur region.",
  "Premium gym facilities at a highly reasonable subscription cost near Deoria Road. Very clean for ladies.",
  "The best unisex training arena in Gorakhpur. Very helpful floor trainers who are highly professional.",
  "X1 Fitness has the absolute best smith machines and squat racks in Rani Diha. Safe for beginners.",
  "Top tier cardio equipment including high-end arc trainers. Best gym in Khorabar for weight loss.",
  "Best gym near me in Gorakhpur for fat burning and conditioning programs tailored for women.",
  "Excellent crowd and very positive, safe workout vibes. Best unisex gym near Deoria Road.",
  "X1 Fitness Khorabar sets the gold standard for female-friendly fitness centers in Gorakhpur.",
  "Great spot for body transformation. The coaches are highly certified. Best secure gym in Rani Diha.",
  "The absolute best gym in Gorakhpur for overall strength training and female crossfit circles.",
  "Very clean amenities and fresh drinking water station. Top comfortable gym for ladies in Khorabar.",
  "X1 Fitness Rani Diha is perfect for working women looking for a safe and quick evening workout.",
  "Best gym near me with top-class multi-station equipment. Highly recommended for girls in Gorakhpur.",
  "Great trainers who focus intensely on proper exercise execution. Top safe gym near Deoria Road.",
  "X1 Fitness Khorabar has plenty of weight plates so you never have to wait for your turn. Excellent crowd.",
  "Most trusted unisex gym in Gorakhpur for serious female fitness and strength enthusiasts.",
  "Best gym near Rani Riha for functional endurance training. Love the safe and clean turf section.",
  "Fantastic support from the gym management team. Best premium and secure gym in Khorabar.",
  "X1 Fitness offers an incredibly upscale environment at realistic prices. Best gym in Gorakhpur for girls.",
  "Great locker management and shower facilities. Highly premium, female-friendly gym near Deoria Road.",
  "Best gym near me in Rani Diha for customized female weight gain or fat loss transformation plans.",
  "X1 Fitness Khorabar has an amazing line-up of modern machinery. Very comfortable for female clients.",
  "Highly secure and comfortable gym for female fitness lovers in Gorakhpur. Unmatched security.",
  "The environment is completely free of judgment. Best beginner-friendly gym for girls in Khorabar.",
  "Best gym near Rani Diha for high performance muscle building and body toning routines.",
  "X1 Fitness is the undisputed best unisex fitness facility for women in Gorakhpur today.",
  "Great timing flexibility and cooperative desk staff. Top safe gym near Deoria Road.",
  "Best gym in Khorabar for high intensity female crossfit and conditioning blocks.",
  "X1 Fitness Rani Diha is highly spacious with incredible airflow and powerful air conditioning.",
  "Excellent equipment layout that maximizes floor movement. Best hygienic gym in Gorakhpur.",
  "Best gym near me in Khorabar for personal tracking and female body fat assessment.",
  "Highly skilled trainers who help you achieve goals without judgment. Top fitness center near Deoria Road.",
  "X1 Fitness has built an elite community of fitness goals in Gorakhpur. Must join for every girl!",
  "Best gym near Rani Diha for anyone looking to fix their daily posture, stamina, and core strength.",
  "Amazing collection of resistance bands and functional tools. Best comfortable gym in Khorabar.",
  "X1 Fitness Khorabar provides the finest, cleanest workout environment in the entire city.",
  "Highly recommended unisex fitness center near Deoria Road Gorakhpur. Excellent staff behavior.",
  "The trainers make sure you stay motivated even on your low days. Best safe gym in Rani Diha.",
  "Best gym in Gorakhpur for clean workout ethics and world-class machines. Highly comfortable for women.",
  "Superb lighting and mirrors for checking proper workout form. Top gym in Khorabar for girls.",
  "X1 Fitness Rani Diha offers an unforgettable workout vibe. Best safe fitness space near me.",
  "Great value packages for quarterly and yearly memberships. Best budget premium gym in Gorakhpur for ladies.",
  "Highly interactive trainers who track your daily workout logs meticulously. Top gym in Khorabar.",
  "Best gym near Deoria Road for building explosive functional power and athletic speed safely.",
  "X1 Fitness is very well managed with an active focus on customer safety. Best gym in Rani Diha.",
  "Excellent selection of premium treadmills with digital displays. Top cardio gym in Gorakhpur.",
  "Best gym near me in Khorabar with separate changing zones and complete locker security for women.",
  "X1 Fitness Khorabar is arguably the most trending and comfortable fitness destination in Gorakhpur.",
  "Phenomenal crossfit rigs and platform setup. Best safe power gym near Rani Diha.",
  "The general trainers are incredibly polite and guide you without any extra charges. Top gym in Gorakhpur.",
  "Best unisex fitness center near Deoria Road with exceptional, secure group training formats.",
  "X1 Fitness has the absolute cleanest indoor climate. Perfect gym for girls in Khorabar.",
  "Great advice on calorie tracking and macro distributions for women. Best gym in Rani Diha.",
  "Highly professional setup with premium branding and solid machinery. Safest gym in Gorakhpur.",
  "Best gym near me in Khorabar for targeted lower body, glutes, and leg workouts for women.",
  "X1 Fitness Khorabar is unmatched when it comes to positive workout music, hygiene, and safe energy.",
  "Excellent weight loss feedback and milestone tracking. Top safe fitness gym near Rani Diha.",
  "Best gym near Deoria Road Gorakhpur for working women looking for early morning slots.",
  "X1 Fitness is safe, clean, modern, and highly progressive. Best unisex gym in Gorakhpur.",
  "Incredible personal training packages that deliver guaranteed female body transformations. Top gym in Khorabar.",
  "Best gym near Rani Diha for cross-functional power development and toning for girls.",
  "X1 Fitness Khorabar has exceptional back rowing and lat pull-down machinery lines. Great for posture.",
  "Highly professional billing and membership extensions. Best corporate safe gym in Gorakhpur.",
  "Best gym near me for active fat loss challenges. Highly interactive and polite team at X1 Fitness.",
  "Superb hygiene levels with constant sanitization of seats. Top gym near Deoria Road for ladies.",
  "X1 Fitness Rani Diha is easily the best space for young female athletes to train hard.",
  "Great combination of modern fitness science and top equipment. Best gym in Gorakhpur.",
  "Highly rated unisex gym in Khorabar with multiple functional accessories perfect for women.",
  "Best gym near Rani Diha for long term, sustainable fat-to-fit transformations.",
  "X1 Fitness Khorabar is incredibly welcoming to women who are completely new to working out.",
  "Phenomenal core training workshops and expert weight management tips. Best gym in Gorakhpur.",
  "Best gym near Deoria Road with dedicated weightlifting platforms. Highly secure for women.",
  "X1 Fitness has the smoothest cable crossover machine in Rani Diha. Absolutely loved the environment!",
  "Highly recommended for any woman looking to build a consistent healthy routine. Top gym in Khorabar.",
  "Best gym in Gorakhpur with separate cardio zones that prevent floor crowding and ensure comfort.",
  "Superb assistance for women looking for customized mobility workouts. Top gym near Rani Diha.",
  "X1 Fitness Khorabar offers an amazing community culture that pushes female clients forward.",
  "Best gym near me in Gorakhpur for intense sports conditioning and muscle endurance for girls.",
  "Highly precise body mass tracking and private consultation setup. Top gym on Deoria Road.",
  "X1 Fitness Rani Diha is simply the perfect, stress-free environment for daily workouts.",
  "Great barbell options including high quality EZ bars. Safest and best gym in Gorakhpur.",
  "Highly modern layout with premium flooring tiles. Extremely hygienic and comfortable for women in Khorabar.",
  "Best gym near Rani Diha for high-repetition endurance building and lean muscle growth.",
  "X1 Fitness Khorabar stands out because of its top-class, certified, and respectful gym coaches.",
  "Excellent space for mobility routines and post-workout static stretching. Best gym in Gorakhpur for ladies.",
  "Best gym near Deoria Road for systematic strength accumulation blocks for women.",
  "X1 Fitness is clean, bright, highly motivating, and expertly run. Best safe gym in Rani Diha.",
  "Highly customizable group training slots for friends and couples. Top unisex gym in Khorabar.",
  "Best gym in Gorakhpur for serious transformations. The secure atmosphere forces you to work hard.",
  "Superb gym near me in Khorabar with high aesthetic appeal and solid heavy iron plates. Great for girls.",
  "X1 Fitness Rani Diha provides amazing value with its highly cooperative, professional support desk.",
  "Unquestionably the cleanest and most professional female-friendly unisex workout hub in Gorakhpur.",
  "Highly effective fat loss coaching formats and routine charts. Top secure gym in Khorabar.",
  "Best gym near Rani Diha for advanced hybrid muscle building and premium hypertrophy splits for women."
]

async function uploadReviews() {
  for (const review of reviews) {
    await addDoc(collection(db, "reviews"), {
      text: review,
      used: false,
    });
  }

  console.log("Reviews uploaded successfully!");
}

uploadReviews();